name: Code Review

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.java'

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # sun_checks.xml 사용 (더 안정적인 설정)
      - name: Download Checkstyle Config
        run: |
          mkdir -p config
          wget https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/sun_checks.xml -O config/checkstyle.xml

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v0.9.5
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          checkstyle_config: config/checkstyle.xml
          level: warning       # 추가: warning 레벨로 설정
          filter_mode: nofilter # 추가: 모든 결과 표시

      - name: Run PMD
        uses: pmd/pmd-github-action@v1
        with:
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml'