name: Code Review

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.java'

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # PMD만 실행
      - name: Run PMD
        uses: pmd/pmd-github-action@v1
        with:
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml'